{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fed-compute.fullname" . }}-secrets
  labels:
    {{- include "fed-compute.labels" . | nindent 4 }}
type: Opaque
stringData:
  OPERATOR_API_KEY: {{ .Values.secrets.OPERATOR_API_KEY | quote }}
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}
  S3_ENDPOINT_URL: {{ .Values.secrets.S3_ENDPOINT_URL | quote }}
  S3_ACCESS_KEY: {{ .Values.secrets.S3_ACCESS_KEY | quote }}
  S3_SECRET_KEY: {{ .Values.secrets.S3_SECRET_KEY | quote }}
{{- end }}
